/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */
import { type AccountMeta, type AccountSignerMeta, type Address, type Codec, type Decoder, type Encoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlySignerAccount, type TransactionSigner, type WritableAccount } from "@solana/kit";
import { TOKEN_2022_PROGRAM_ADDRESS } from '../programs';
export declare const BURN_CHECKED_DISCRIMINATOR = 15;
export declare function getBurnCheckedDiscriminatorBytes(): import("@solana/kit").ReadonlyUint8Array;
export type BurnCheckedInstruction<TProgram extends string = typeof TOKEN_2022_PROGRAM_ADDRESS, TAccountAccount extends string | AccountMeta<string> = string, TAccountMint extends string | AccountMeta<string> = string, TAccountAuthority extends string | AccountMeta<string> = string, TRemainingAccounts extends readonly AccountMeta<string>[] = []> = Instruction<TProgram> & InstructionWithData<Uint8Array> & InstructionWithAccounts<[
    TAccountAccount extends string ? WritableAccount<TAccountAccount> : TAccountAccount,
    TAccountMint extends string ? WritableAccount<TAccountMint> : TAccountMint,
    TAccountAuthority extends string ? ReadonlyAccount<TAccountAuthority> : TAccountAuthority,
    ...TRemainingAccounts
]>;
export type BurnTokenInstructionData = {
    discriminator: number;
    /** The amount of tokens to burn. */
    amount: bigint;
    /** Expected number of base 10 digits to the right of the decimal place. */
    decimals: number;
};
export type BurnTokenInstructionDataArgs = {
    /** The amount of tokens to burn. */
    amount: number | bigint;
    /** Expected number of base 10 digits to the right of the decimal place. */
    decimals: number;
};
export declare function burnTokenInstructionDataEncoder(): Encoder<BurnTokenInstructionDataArgs>;
export declare function burnTokenInstructionDataDecoder(): Decoder<BurnTokenInstructionData>;
export declare function burnTokenInstructionDataCodec(): Codec<BurnTokenInstructionDataArgs, BurnTokenInstructionData>;
export type BurnCheckedInput<TAccountAccount extends string = string, TAccountMint extends string = string, TAccountAuthority extends string = string> = {
    /** The account to burn from. */
    account: Address<TAccountAccount>;
    /** The token mint. */
    mint: Address<TAccountMint>;
    /** The account's owner/delegate or its multisignature account. */
    owner: TransactionSigner<TAccountAuthority>;
    amount: BurnTokenInstructionDataArgs['amount'];
    decimals: BurnTokenInstructionDataArgs['decimals'];
    multiSigners?: Array<TransactionSigner>;
};
export declare function burnToken<TAccountAccount extends string, TAccountMint extends string, TAccountAuthority extends string, TProgramAddress extends Address = typeof TOKEN_2022_PROGRAM_ADDRESS>(input: BurnCheckedInput<TAccountAccount, TAccountMint, TAccountAuthority>, config?: {
    programAddress?: TProgramAddress;
}): BurnCheckedInstruction<TProgramAddress, TAccountAccount, TAccountMint, (typeof input)['owner'] extends TransactionSigner<TAccountAuthority> ? ReadonlySignerAccount<TAccountAuthority> & AccountSignerMeta<TAccountAuthority> : TAccountAuthority>;
export type ParsedBurnCheckedInstruction<TProgram extends string = typeof TOKEN_2022_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = {
    programAddress: Address<TProgram>;
    accounts: {
        /** The account to burn from. */
        account: TAccountMetas[0];
        /** The token mint. */
        mint: TAccountMetas[1];
        /** The account's owner/delegate or its multisignature account. */
        owner: TAccountMetas[2];
    };
    data: BurnTokenInstructionData;
};
export declare function parseBurnCheckedInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<Uint8Array>): ParsedBurnCheckedInstruction<TProgram, TAccountMetas>;
//# sourceMappingURL=burnChecked.d.ts.map
